// Generated by CoffeeScript 1.6.2
/*
grunt-typo3-phpunit

Copyright (c) 2013 Andreas Lappe
http://kaeufli.ch
Licensed under the BSD license.
*/


(function() {
  module.exports = function(grunt) {
    var phpunit;

    phpunit = (require('./lib/typo3-phpunit')).init(grunt);
    return grunt.registerMultiTask('typo3-phpunit', 'Run the cli-dispatcher of the TYPO3 extension phpunit', function() {
      phpunit.setup(this);
      return phpunit.run();
    });
  };

}).call(this);
