// Generated by CoffeeScript 1.9.0

/*
grunt-typo3-phpunit

Copyright (c) 2015 Andreas Lappe
http://zimmer7.com
Licensed under the BSD license.
 */

(function() {
  module.exports = function(grunt) {
    var phpunit;
    phpunit = (require('./lib/typo3-phpunit')).init(grunt);
    return grunt.registerMultiTask('typo3-phpunit', 'Run the included phpunit', function() {
      phpunit.setup(this);
      return phpunit.run();
    });
  };

}).call(this);
